name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_STANDARD: true